name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "you@gmail.com"
          git config --global user.name "purushottam-angadi"
          git remote add space https://purushottamangadi21:$HF_TOKEN@huggingface.co/spaces/purushottamangadi21/AI-Video-Assistant
          git push space main --force